### PR TITLE
LootGames 2.0

### PR DESCRIPTION
**Pull request by TimeConqueror**
So, here's a couple of things:
- Added Minesweeper
- Rewritten Game Of Light with improved and lag-protected visual effects
- Old Game Of Light Tile Entities will be automatically converted back to Puzzle Master
- Old configs will be automatically migrated to their new versions.

### CODE REVIEW

**Comment by Dream-Master** [comment]
@repo @glease hope you can review this.

**Comment by repo-alt** [comment]
@Dream-Master You tagged some random guy

**Comment by Dream-Master** [comment]
yes. If you cant review it np i can ask others too

**Comment by TimeConqueror** [comment]
Welp, for some reason the minigame doesn't respond on left clicks for now on thermos servers. So before fixing this don't merge the pull request

Upd: fixed

**Comment by Glease** [comment]
200+ file change and 180+ source file changed. Who on earth can review this?

**Comment by repo-alt** [comment]
I looked through about a third and gave up

**Review by repo-alt — APPROVED** [review]
Superficial browsing shows nothing criminal. It is essentially a new mod so I propose to add it and test ingame.

**Pull request merged**
